# CMake generated Testfile for 
# Source directory: /home/runner/work/ubpf/ubpf/custom_tests
# Build directory: /home/runner/work/ubpf/ubpf/build-tests/custom_tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ubpf_test_atomic_validate-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_atomic_validate.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_atomic_validate")
set_tests_properties(ubpf_test_atomic_validate-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_constant_blinding-Custom "/home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_constant_blinding")
set_tests_properties(ubpf_test_constant_blinding-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;61;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_custom_local_function_stack_size-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_custom_local_function_stack_size.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_custom_local_function_stack_size")
set_tests_properties(ubpf_test_custom_local_function_stack_size-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_custom_local_function_stack_size_unaligned-Custom "/home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_custom_local_function_stack_size_unaligned")
set_tests_properties(ubpf_test_custom_local_function_stack_size_unaligned-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;61;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_custom_local_function_stack_size_zero-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_custom_local_function_stack_size_zero.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_custom_local_function_stack_size_zero")
set_tests_properties(ubpf_test_custom_local_function_stack_size_zero-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_debug_function-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_debug_function.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_debug_function")
set_tests_properties(ubpf_test_debug_function-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_default_dispatcher_helper_context-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_default_dispatcher_helper_context.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_default_dispatcher_helper_context")
set_tests_properties(ubpf_test_default_dispatcher_helper_context-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_default_local_function_stack_size-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_default_local_function_stack_size.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_default_local_function_stack_size")
set_tests_properties(ubpf_test_default_local_function_stack_size-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_external_dispatcher_context_overwrite-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_external_dispatcher_context_overwrite.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_external_dispatcher_context_overwrite")
set_tests_properties(ubpf_test_external_dispatcher_context_overwrite-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_external_dispatcher_simple_context-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_external_dispatcher_simple_context.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_external_dispatcher_simple_context")
set_tests_properties(ubpf_test_external_dispatcher_simple_context-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_frame_pointer-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_frame_pointer.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_frame_pointer")
set_tests_properties(ubpf_test_frame_pointer-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_jit_buffer_too_small-Custom "/home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_jit_buffer_too_small")
set_tests_properties(ubpf_test_jit_buffer_too_small-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;61;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_jit_unexpected_instruction-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_jit_unexpected_instruction.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_jit_unexpected_instruction")
set_tests_properties(ubpf_test_jit_unexpected_instruction-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_readonly_bytecode-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_readonly_bytecode.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_readonly_bytecode")
set_tests_properties(ubpf_test_readonly_bytecode-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_update_dispatcher-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_update_dispatcher.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_update_dispatcher")
set_tests_properties(ubpf_test_update_dispatcher-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
add_test(ubpf_test_update_helpers-Custom "sh" "-c" "cat /home/runner/work/ubpf/ubpf/custom_tests/data/ubpf_test_update_helpers.input |  /home/runner/work/ubpf/ubpf/build-tests/bin/ubpf_test_update_helpers")
set_tests_properties(ubpf_test_update_helpers-Custom PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;55;add_test;/home/runner/work/ubpf/ubpf/custom_tests/CMakeLists.txt;0;")
