#
# Copyright (c) 2022-present, IO Visor Project
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: arm64

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: Ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Setup ARM64
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Create build container
      run: \
        docker create --platform linux/arm64 --name build_container \
        -v ${{ github.workspace }}:/home/builder/src \
        -w /home/builder/src \
        tail -f /dev/null

    - name: Install system dependencies (Linux)
      run: |
        export RUN="docker exec build_container"
        ${RUN} apt-get update
        ${RUN} apt-get install -y \
          build-essential \
          ccache \
          ninja-build \
          cmake \
          git

    - name: Configure the project
      run: |
        export RUN="docker exec build_container"

        ${RUN} cmake \
          -G Ninja \
          -S . \
          -B build \
          -DCMAKE_BUILD_TYPE=Debug \
          -DUBPF_ENABLE_TESTS=true \
          -DUBPF_ENABLE_INSTALL=true

    - name: Build the project
      run: |
        export RUN="docker exec build_container"
        ${RUN} cmake \
          --build build \
          -- -v

    - name: Run the tests
      run: |
        export RUN="docker exec build_container"
        ${RUN} cmake \
          --build build \
          --target test \
          -- -v
